name: "GitHub API Fetch"
author: "Kai Kimera <mail@kai.kim>"
description: "GitHub Action to get GitHub API responses and save them to repository."
branding:
  icon: "anchor"
  color: "gray-dark"
inputs:
  git_repo:
    description: "Git Repository"
    required: true
  git_user:
    description: "Git User"
    required: true
  git_email:
    description: "Git E-mail"
    required: true
  git_token:
    description: "Git Token"
    required: true
  api_dir:
    description: "GitHub API Local Directory"
    required: true
    default: "api/github"
  api_type:
    description: "GitHub API Type"
    required: true
    default: "orgs"
  api_owner:
    description: "GitHub API Owner"
    required: true
  api_token:
    description: "GitHub API Token"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.git_repo }}
    - ${{ inputs.git_user }}
    - ${{ inputs.git_email }}
    - ${{ inputs.git_token }}
    - ${{ inputs.api_dir }}
    - ${{ inputs.api_type }}
    - ${{ inputs.api_owner }}
    - ${{ inputs.api_token }}
